max_photo_count: 4
spaces: " 　"
facebook:
  app_id: '261336187341371'
photo_bbs:
  top_directory: '/home/hiro/foveon'
  data_path: '/home/hiro/foveon/bbs-utf8.txt'
  separator: '<>'
  photos: 4
admin:
  messages:
    per_page: 30
